server:
  port: 8081

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0



  datasource:
    type: com.zaxxer.hikari.HikariDataSource  #显示指定hikari连接池
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/test #url
    username: root  #用户名
    password: root  #密码
    hikari:
      max-lifetime: 0  # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 5 # 连接池最大连接数，默认是10
      minimum-idle: 10
      connection-test-query: select 1

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.example.provider.entity #配置实体类


